/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVolunteerRouteImport } from './routes/app.volunteer'
import { Route as AppMentorRouteImport } from './routes/app.mentor'
import { Route as AppDonorRouteImport } from './routes/app.donor'
import { Route as AppVolunteerUpcomingRouteImport } from './routes/app.volunteer.upcoming'
import { Route as AppVolunteerCompletedRouteImport } from './routes/app.volunteer.completed'
import { Route as AppVolunteerCertificatesRouteImport } from './routes/app.volunteer.certificates'
import { Route as AppVolunteerApplicationsRouteImport } from './routes/app.volunteer.applications'
import { Route as AppMentorSessionsRouteImport } from './routes/app.mentor.sessions'
import { Route as AppMentorMenteesRouteImport } from './routes/app.mentor.mentees'
import { Route as AppDonorSavedRouteImport } from './routes/app.donor.saved'
import { Route as AppDonorImpactRouteImport } from './routes/app.donor.impact'
import { Route as AppDonorFollowingRouteImport } from './routes/app.donor.following'
import { Route as AppDonorDonationsRouteImport } from './routes/app.donor.donations'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVolunteerRoute = AppVolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorRoute = AppMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorRoute = AppDonorRouteImport.update({
  id: '/donor',
  path: '/donor',
  getParentRoute: () => AppRoute,
} as any)
const AppVolunteerUpcomingRoute = AppVolunteerUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AppVolunteerRoute,
} as any)
const AppVolunteerCompletedRoute = AppVolunteerCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => AppVolunteerRoute,
} as any)
const AppVolunteerCertificatesRoute =
  AppVolunteerCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AppVolunteerRoute,
  } as any)
const AppVolunteerApplicationsRoute =
  AppVolunteerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AppVolunteerRoute,
  } as any)
const AppMentorSessionsRoute = AppMentorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppMentorRoute,
} as any)
const AppMentorMenteesRoute = AppMentorMenteesRouteImport.update({
  id: '/mentees',
  path: '/mentees',
  getParentRoute: () => AppMentorRoute,
} as any)
const AppDonorSavedRoute = AppDonorSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppDonorRoute,
} as any)
const AppDonorImpactRoute = AppDonorImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AppDonorRoute,
} as any)
const AppDonorFollowingRoute = AppDonorFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AppDonorRoute,
} as any)
const AppDonorDonationsRoute = AppDonorDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AppDonorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/institutions': typeof InstitutionsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stories': typeof StoriesRoute
  '/volunteer': typeof VolunteerRoute
  '/app/donor': typeof AppDonorRouteWithChildren
  '/app/mentor': typeof AppMentorRouteWithChildren
  '/app/volunteer': typeof AppVolunteerRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/donor/donations': typeof AppDonorDonationsRoute
  '/app/donor/following': typeof AppDonorFollowingRoute
  '/app/donor/impact': typeof AppDonorImpactRoute
  '/app/donor/saved': typeof AppDonorSavedRoute
  '/app/mentor/mentees': typeof AppMentorMenteesRoute
  '/app/mentor/sessions': typeof AppMentorSessionsRoute
  '/app/volunteer/applications': typeof AppVolunteerApplicationsRoute
  '/app/volunteer/certificates': typeof AppVolunteerCertificatesRoute
  '/app/volunteer/completed': typeof AppVolunteerCompletedRoute
  '/app/volunteer/upcoming': typeof AppVolunteerUpcomingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/institutions': typeof InstitutionsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stories': typeof StoriesRoute
  '/volunteer': typeof VolunteerRoute
  '/app/donor': typeof AppDonorRouteWithChildren
  '/app/mentor': typeof AppMentorRouteWithChildren
  '/app/volunteer': typeof AppVolunteerRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/donor/donations': typeof AppDonorDonationsRoute
  '/app/donor/following': typeof AppDonorFollowingRoute
  '/app/donor/impact': typeof AppDonorImpactRoute
  '/app/donor/saved': typeof AppDonorSavedRoute
  '/app/mentor/mentees': typeof AppMentorMenteesRoute
  '/app/mentor/sessions': typeof AppMentorSessionsRoute
  '/app/volunteer/applications': typeof AppVolunteerApplicationsRoute
  '/app/volunteer/certificates': typeof AppVolunteerCertificatesRoute
  '/app/volunteer/completed': typeof AppVolunteerCompletedRoute
  '/app/volunteer/upcoming': typeof AppVolunteerUpcomingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/explore': typeof ExploreRoute
  '/institutions': typeof InstitutionsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/stories': typeof StoriesRoute
  '/volunteer': typeof VolunteerRoute
  '/app/donor': typeof AppDonorRouteWithChildren
  '/app/mentor': typeof AppMentorRouteWithChildren
  '/app/volunteer': typeof AppVolunteerRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/donor/donations': typeof AppDonorDonationsRoute
  '/app/donor/following': typeof AppDonorFollowingRoute
  '/app/donor/impact': typeof AppDonorImpactRoute
  '/app/donor/saved': typeof AppDonorSavedRoute
  '/app/mentor/mentees': typeof AppMentorMenteesRoute
  '/app/mentor/sessions': typeof AppMentorSessionsRoute
  '/app/volunteer/applications': typeof AppVolunteerApplicationsRoute
  '/app/volunteer/certificates': typeof AppVolunteerCertificatesRoute
  '/app/volunteer/completed': typeof AppVolunteerCompletedRoute
  '/app/volunteer/upcoming': typeof AppVolunteerUpcomingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/explore'
    | '/institutions'
    | '/login'
    | '/register'
    | '/stories'
    | '/volunteer'
    | '/app/donor'
    | '/app/mentor'
    | '/app/volunteer'
    | '/app/'
    | '/app/donor/donations'
    | '/app/donor/following'
    | '/app/donor/impact'
    | '/app/donor/saved'
    | '/app/mentor/mentees'
    | '/app/mentor/sessions'
    | '/app/volunteer/applications'
    | '/app/volunteer/certificates'
    | '/app/volunteer/completed'
    | '/app/volunteer/upcoming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/explore'
    | '/institutions'
    | '/login'
    | '/register'
    | '/stories'
    | '/volunteer'
    | '/app/donor'
    | '/app/mentor'
    | '/app/volunteer'
    | '/app'
    | '/app/donor/donations'
    | '/app/donor/following'
    | '/app/donor/impact'
    | '/app/donor/saved'
    | '/app/mentor/mentees'
    | '/app/mentor/sessions'
    | '/app/volunteer/applications'
    | '/app/volunteer/certificates'
    | '/app/volunteer/completed'
    | '/app/volunteer/upcoming'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/explore'
    | '/institutions'
    | '/login'
    | '/register'
    | '/stories'
    | '/volunteer'
    | '/app/donor'
    | '/app/mentor'
    | '/app/volunteer'
    | '/app/'
    | '/app/donor/donations'
    | '/app/donor/following'
    | '/app/donor/impact'
    | '/app/donor/saved'
    | '/app/mentor/mentees'
    | '/app/mentor/sessions'
    | '/app/volunteer/applications'
    | '/app/volunteer/certificates'
    | '/app/volunteer/completed'
    | '/app/volunteer/upcoming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ExploreRoute: typeof ExploreRoute
  InstitutionsRoute: typeof InstitutionsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StoriesRoute: typeof StoriesRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/volunteer': {
      id: '/app/volunteer'
      path: '/volunteer'
      fullPath: '/app/volunteer'
      preLoaderRoute: typeof AppVolunteerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentor': {
      id: '/app/mentor'
      path: '/mentor'
      fullPath: '/app/mentor'
      preLoaderRoute: typeof AppMentorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donor': {
      id: '/app/donor'
      path: '/donor'
      fullPath: '/app/donor'
      preLoaderRoute: typeof AppDonorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/volunteer/upcoming': {
      id: '/app/volunteer/upcoming'
      path: '/upcoming'
      fullPath: '/app/volunteer/upcoming'
      preLoaderRoute: typeof AppVolunteerUpcomingRouteImport
      parentRoute: typeof AppVolunteerRoute
    }
    '/app/volunteer/completed': {
      id: '/app/volunteer/completed'
      path: '/completed'
      fullPath: '/app/volunteer/completed'
      preLoaderRoute: typeof AppVolunteerCompletedRouteImport
      parentRoute: typeof AppVolunteerRoute
    }
    '/app/volunteer/certificates': {
      id: '/app/volunteer/certificates'
      path: '/certificates'
      fullPath: '/app/volunteer/certificates'
      preLoaderRoute: typeof AppVolunteerCertificatesRouteImport
      parentRoute: typeof AppVolunteerRoute
    }
    '/app/volunteer/applications': {
      id: '/app/volunteer/applications'
      path: '/applications'
      fullPath: '/app/volunteer/applications'
      preLoaderRoute: typeof AppVolunteerApplicationsRouteImport
      parentRoute: typeof AppVolunteerRoute
    }
    '/app/mentor/sessions': {
      id: '/app/mentor/sessions'
      path: '/sessions'
      fullPath: '/app/mentor/sessions'
      preLoaderRoute: typeof AppMentorSessionsRouteImport
      parentRoute: typeof AppMentorRoute
    }
    '/app/mentor/mentees': {
      id: '/app/mentor/mentees'
      path: '/mentees'
      fullPath: '/app/mentor/mentees'
      preLoaderRoute: typeof AppMentorMenteesRouteImport
      parentRoute: typeof AppMentorRoute
    }
    '/app/donor/saved': {
      id: '/app/donor/saved'
      path: '/saved'
      fullPath: '/app/donor/saved'
      preLoaderRoute: typeof AppDonorSavedRouteImport
      parentRoute: typeof AppDonorRoute
    }
    '/app/donor/impact': {
      id: '/app/donor/impact'
      path: '/impact'
      fullPath: '/app/donor/impact'
      preLoaderRoute: typeof AppDonorImpactRouteImport
      parentRoute: typeof AppDonorRoute
    }
    '/app/donor/following': {
      id: '/app/donor/following'
      path: '/following'
      fullPath: '/app/donor/following'
      preLoaderRoute: typeof AppDonorFollowingRouteImport
      parentRoute: typeof AppDonorRoute
    }
    '/app/donor/donations': {
      id: '/app/donor/donations'
      path: '/donations'
      fullPath: '/app/donor/donations'
      preLoaderRoute: typeof AppDonorDonationsRouteImport
      parentRoute: typeof AppDonorRoute
    }
  }
}

interface AppDonorRouteChildren {
  AppDonorDonationsRoute: typeof AppDonorDonationsRoute
  AppDonorFollowingRoute: typeof AppDonorFollowingRoute
  AppDonorImpactRoute: typeof AppDonorImpactRoute
  AppDonorSavedRoute: typeof AppDonorSavedRoute
}

const AppDonorRouteChildren: AppDonorRouteChildren = {
  AppDonorDonationsRoute: AppDonorDonationsRoute,
  AppDonorFollowingRoute: AppDonorFollowingRoute,
  AppDonorImpactRoute: AppDonorImpactRoute,
  AppDonorSavedRoute: AppDonorSavedRoute,
}

const AppDonorRouteWithChildren = AppDonorRoute._addFileChildren(
  AppDonorRouteChildren,
)

interface AppMentorRouteChildren {
  AppMentorMenteesRoute: typeof AppMentorMenteesRoute
  AppMentorSessionsRoute: typeof AppMentorSessionsRoute
}

const AppMentorRouteChildren: AppMentorRouteChildren = {
  AppMentorMenteesRoute: AppMentorMenteesRoute,
  AppMentorSessionsRoute: AppMentorSessionsRoute,
}

const AppMentorRouteWithChildren = AppMentorRoute._addFileChildren(
  AppMentorRouteChildren,
)

interface AppVolunteerRouteChildren {
  AppVolunteerApplicationsRoute: typeof AppVolunteerApplicationsRoute
  AppVolunteerCertificatesRoute: typeof AppVolunteerCertificatesRoute
  AppVolunteerCompletedRoute: typeof AppVolunteerCompletedRoute
  AppVolunteerUpcomingRoute: typeof AppVolunteerUpcomingRoute
}

const AppVolunteerRouteChildren: AppVolunteerRouteChildren = {
  AppVolunteerApplicationsRoute: AppVolunteerApplicationsRoute,
  AppVolunteerCertificatesRoute: AppVolunteerCertificatesRoute,
  AppVolunteerCompletedRoute: AppVolunteerCompletedRoute,
  AppVolunteerUpcomingRoute: AppVolunteerUpcomingRoute,
}

const AppVolunteerRouteWithChildren = AppVolunteerRoute._addFileChildren(
  AppVolunteerRouteChildren,
)

interface AppRouteChildren {
  AppDonorRoute: typeof AppDonorRouteWithChildren
  AppMentorRoute: typeof AppMentorRouteWithChildren
  AppVolunteerRoute: typeof AppVolunteerRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDonorRoute: AppDonorRouteWithChildren,
  AppMentorRoute: AppMentorRouteWithChildren,
  AppVolunteerRoute: AppVolunteerRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ExploreRoute: ExploreRoute,
  InstitutionsRoute: InstitutionsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StoriesRoute: StoriesRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
